---
- name: Configure carbon-cache systemd service
  ansible.builtin.copy:
    src: systemd/carbon-cache.service
    dest: /etc/systemd/system/carbon-cache.service
    mode: "0644"

- name: Write config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ graphite_carbon_confdir }}/{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: templates/carbon/carbon.conf.j2, dest: carbon.conf }
    - { src: templates/carbon/storage-schemas.conf.j2, dest: storage-schemas.conf }
    - { src: templates/carbon/storage-aggregation.conf.j2, dest: storage-aggregation.conf }
  notify:
    - Restart carbon cache
    - Makemigrations

- name: Write graphite-web configuration
  ansible.builtin.template:
    src: templates/graphite-web/local_settings.py.j2
    dest: "{{ graphite_web_confdir }}/local_settings.py"
    mode: "0644"

- name: Initialize database
  ansible.builtin.command: /opt/graphite/bin/django-admin.py migrate --settings=graphite.settings --run-syncdb
  environment:
    PYTHONPATH: /opt/graphite/lib/:/opt/graphite/webapp/
  register: graphite_register_db_init
  changed_when: graphite_register_db_init.stdout is not search("No migrations to apply")

- name: Collect static files
  ansible.builtin.command: /opt/graphite/bin/django-admin.py collectstatic --settings=graphite.settings --noinput
  environment:
    PYTHONPATH: /opt/graphite/lib/:/opt/graphite/webapp/
  args:
    creates: "{{ graphite_web_staticdir }}"

- name: Make sure webserver can read webfiles
  ansible.builtin.file:
    path: /opt/graphite/storage
    state: directory
    recurse: true
    owner: www-data
    group: www-data

- name: Make sure webserver can read webfiles
  ansible.builtin.file:
    path: /opt/graphite/cache
    state: directory
    recurse: true
    owner: www-data
    group: www-data

- name: Copy systemd unit for graphite-web
  ansible.builtin.template:
    src: templates/graphite-web/graphite-web.service.j2
    dest: /etc/systemd/system/graphite-web.service
    mode: "0644"

- name: Enable carbon-cache service
  ansible.builtin.systemd:
    name: carbon-cache
    daemon_reload: true
    enabled: true
    state: started

- name: Enable and start graphite-web service
  ansible.builtin.systemd:
    name: graphite-web
    daemon_reload: true
    enabled: true
    state: started
