---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ graphite_requirements }}"
  register: graphite_register_rpms_installed
  until: graphite_register_rpms_installed is success
  retries: 10
  delay: 2

- name: Install whisper
  ansible.builtin.pip:
    name: https://github.com/graphite-project/whisper/tarball/master
    virtualenv: /opt/graphite
    virtualenv_command: virtualenv
    extra_args: "--no-binary=:all:"
  environment:
    PYTHONPATH: /opt/graphite/lib/:/opt/graphite/webapp/

- name: Install carbon
  ansible.builtin.pip:
    name: https://github.com/graphite-project/carbon/tarball/master
    virtualenv: /opt/graphite
    virtualenv_command: virtualenv
    extra_args: "--no-binary=:all:"
  environment:
    PYTHONPATH: /opt/graphite/lib/:/opt/graphite/webapp/

- name: Install graphite-web
  ansible.builtin.pip:
    name: https://github.com/graphite-project/graphite-web/tarball/master
    virtualenv: /opt/graphite
    virtualenv_command: virtualenv
    extra_args: "--no-binary=:all:"
  environment:
    PYTHONPATH: /opt/graphite/lib/:/opt/graphite/webapp/
