---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - role::graphite
    - role::graphite:install
    - role::graphite:config

- name: Import installation tasks
  ansible.builtin.import_tasks: installation.yml
  tags:
    - role::graphite
    - role::graphite:install

- name: Import configuration tasks
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - role::graphite
    - role::graphite:config
